language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt --allow-external PIL --allow-unverified PIL --download-cache $HOME/.pip-cache
    - pip install coveralls
    - pip install coverage
# command to run tests, e.g. python setup.py test
script:
    coverage run --source=med_social manage.py test
after_success:
  coveralls

env: DB=postgres
addons:
  postgresql: "9.3"
before_script:
  - psql template1 -c "create schema extensions;" -U postgres
  - psql template1 -c "grant all on schema extensions to public;" -U postgres
  - psql template1 -c "grant all on schema extensions to postgres;" -U postgres
  - psql template1 -c "create extension hstore with schema extensions;" -U postgres
  - psql -c 'create database test_db;' -U postgres
  - psql test_db -c "grant all on database test_db to public;" -U postgres
  - psql test_db -c "grant all on database test_db to postgres;" -U postgres
before_install:
    #  - sudo apt-get update -qq
  - sudo apt-get install -y libgeos-c1 libjpeg62 libjpeg-dev zlib1g-dev imagemagick libevent-dev redis-server libfreetype6-dev libxml2 libxslt1-dev libxml2-dev libxslt-dev node-less
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
    - node_modules
notifications:
  flowdock: test123
